I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 303, in script
    jump sair_de_casa
ScriptError: could not find label 'sair_de_casa'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 303, in script
    jump sair_de_casa
  File "C:\Users\5304\Downloads\instaladores\renpy-8.2.1-sdk\renpy\ast.py", line 1698, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\5304\Downloads\instaladores\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'sair_de_casa'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.2.1.24030407
testeandancas2 1.0
Fri Nov 29 16:18:00 2024
